version: '2.3'
services:
  django:
    image: layermapping-spatialite
    build:
      context: ./layermapping
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8112:8080"
    volumes:
      - ./layermapping:/usr/src
