version: '2.3'
services:
  database:
    image: mysql/mysql-server
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    ports:
      - "3306:3306"
  django:
    image: layermapping-app
    build:
      context: ./layermapping
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "8112:8080"
    links:
      - database:database.service.layermapping.internal
    volumes:
      - ./layermapping:/usr/src
