#!/bin/bash

set -ex

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Build app docker containers and run migrations.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose build

        docker-compose up -d database django

        # migrations
        docker-compose \
            run --rm --entrypoint python \
            django manage.py migrate --noinput

        # collectstatic
        docker-compose \
            run --rm --entrypoint python \
            django manage.py collectstatic --noinput

        # use client from django container to grant DB permissions
        # needed to create test databases
        docker-compose \
            run --rm --entrypoint mysql \
            django -hdatabase.service.layermapping.internal -uroot -playermappingroot \
            -e "GRANT ALL ON *.* TO 'layermapping'; FLUSH PRIVILEGES;"

        docker-compose kill database django \
            && docker-compose rm -f database django
    fi
fi
