#!/bin/bash

set -ex

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Build app docker containers and run migrations.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose build

        docker-compose up -d database django

        sleep 2

        # Cannot connect to mysql server via docker-compose.
        # Use client from django container to grant DB permissions
        # needed to create test databases
        docker exec -it mysql mysql -uroot -playermappingroot -hlocalhost \
            -e "GRANT ALL ON *.* TO 'layermapping'; FLUSH PRIVILEGES;"

        sleep 2

        # migrations
        docker-compose \
            run --rm --entrypoint python \
            django manage.py migrate --noinput

        # collectstatic
        docker-compose \
            run --rm --entrypoint python \
            django manage.py collectstatic --noinput

        docker-compose kill database django \
            && docker-compose rm -f database django
    fi
fi
