#!/bin/bash

set -e

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Run python GIS tests from Django core with MySQL.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose up -d database django

        sleep 2

        # use client from django container to grant DB permissions
        # needed to create test databases
        docker exec -it mysql mysql -uroot -playermappingroot -hlocalhost \
            -e "GRANT ALL ON *.* TO 'layermapping'; FLUSH PRIVILEGES;"

        sleep 2

        # Django tests
        echo "Running core Django tests for gis_tests module with MySQL"
        docker-compose \
            run --rm --entrypoint python \
            -e PYTHONPATH="${PYTHONPATH}:/usr/src/test_mysql.py" \
            -e DJANGO_SETTINGS_MODULE='test_mysql' \
            django /usr/local/src/django/tests/runtests.py gis_tests --settings=test_mysql
        echo "Tests complete"

        docker-compose kill database django \
            && docker-compose rm -f database django
    fi
fi
