#!/bin/bash

set -e

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Run python tests from Django core with MySQL.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose up -d database django

        # use client from django container to grant DB permissions
        # needed to create test databases
        docker-compose \
            run --rm --entrypoint mysql \
            django -hdatabase.service.layermapping.internal -uroot -playermappingroot \
            -e "GRANT ALL ON *.* TO 'layermapping'; FLUSH PRIVILEGES;"

        # Django tests
        echo "Running core Django tests with MySQL"
        docker-compose \
            run --rm --entrypoint python \
            -e PYTHONPATH="${PYTHONPATH}:/usr/src/test_mysql.py" \
            -e DJANGO_SETTINGS_MODULE='test_mysql' \
            django /usr/local/src/django/tests/runtests.py --settings=test_mysql
        echo "Tests complete"

        docker-compose kill django database \
            && docker-compose rm -f django database
    fi
fi
