#!/bin/bash

set -e

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Run full tox test suite on Django core with PostGIS.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose up -d database django

        # Django tests
        echo "Running core Django tests via tox with PostGIS"
        docker-compose \
            run --rm --entrypoint tox \
            -e TOX_WORK_DIR=/usr/local/src/django \
            -e PYTHONPATH="${PYTHONPATH}:/usr/local/src/django/test_postgis.py:/usr/local/lib/python3.6/site-packages/" \
            -e DJANGO_SETTINGS_MODULE='test_postgis' \
            -w /usr/local/src/django \
            django
        echo "Tests complete"

        docker-compose kill django \
            && docker-compose rm -f django
    fi
fi
