#!/bin/bash

set -e

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Run full tox test suite on Django core with MySQL.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose up -d database django

        sleep 2

        # use client from django container to grant DB permissions
        # needed to create test databases
        docker-compose \
            run --rm --entrypoint mysql \
            django -hdatabase.service.layermapping.internal -uroot -playermappingroot \
            -e "GRANT ALL ON *.* TO 'layermapping'; FLUSH PRIVILEGES;"

        sleep 2

        # Django tests
        echo "Running core Django tests via tox with MySQL"
        docker-compose \
            run --rm --entrypoint tox \
            -e TOX_WORK_DIR=/usr/local/src/django \
            -e PYTHONPATH="${PYTHONPATH}:/usr/local/src/django/test_mysql.py" \
            -e DJANGO_SETTINGS_MODULE='test_mysql' \
            -w /usr/local/src/django \
            django
        echo "Tests complete"

        docker-compose kill database django \
            && docker-compose rm -f database django
    fi
fi
