#!/bin/bash

set -e

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Run python GIS tests from Django core with PostGIS.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose up -d database django

        # Django tests
        echo "Running core Django tests for gis_tests module with PostGIS"
        docker-compose \
            run --rm --entrypoint python3 \
            -e PYTHONPATH="${PYTHONPATH}:/usr/src/test_postgis.py" \
            -e DJANGO_SETTINGS_MODULE='test_postgis' \
            django /usr/local/src/django/tests/runtests.py gis_tests --settings=test_postgis
        echo "Tests complete"

        docker-compose kill django \
            && docker-compose rm -f django
    fi
fi
