#!/bin/bash

set -ex

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Run Django app server.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose up
    fi
fi
