#!/bin/bash

set -e

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Run python tests and linter.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose up -d database django

        # use client from django container to grant DB permissions
        # needed to create test databases
        docker-compose \
            run --rm --entrypoint mysql \
            django -hdatabase.service.layermapping.internal -uroot -playermappingroot \
            -e "GRANT ALL ON *.* TO 'layermapping'; FLUSH PRIVILEGES;"

        # Django tests
        echo "Running tests"
        docker-compose \
            run --rm --entrypoint python \
            django manage.py test
        echo "Tests complete"

        # Django linting
        echo "Running linter"
        docker-compose \
            run --rm --entrypoint flake8 django
        echo "Linting complete"

        docker-compose kill database django \
            && docker-compose rm -f database django
    fi
fi
