# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demogeomodel',
            name='uuid',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
